# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue May 16 14:32:44 2017
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(265, 276)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/usr/share/pixmaps/gost-crypto-gui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnSign = QtGui.QPushButton(self.centralwidget)
        self.btnSign.setObjectName("btnSign")
        self.verticalLayout.addWidget(self.btnSign)
        self.btnVerify = QtGui.QPushButton(self.centralwidget)
        self.btnVerify.setObjectName("btnVerify")
        self.verticalLayout.addWidget(self.btnVerify)
        self.btnEncrypt = QtGui.QPushButton(self.centralwidget)
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.verticalLayout.addWidget(self.btnEncrypt)
        self.btnDecrypt = QtGui.QPushButton(self.centralwidget)
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.verticalLayout.addWidget(self.btnDecrypt)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 265, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.cryptoprovider = QtGui.QMenu(self.menu)
        self.cryptoprovider.setObjectName("cryptoprovider")
        self.encoding = QtGui.QMenu(self.menu)
        self.encoding.setObjectName("encoding")
        self.sign_check = QtGui.QMenu(self.menu)
        self.sign_check.setObjectName("sign_check")
        self.dettached = QtGui.QMenu(self.menu)
        self.dettached.setObjectName("dettached")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_CSP = QtGui.QAction(MainWindow)
        self.action_CSP.setCheckable(True)
        self.action_CSP.setChecked(True)
        self.action_CSP.setObjectName("action_CSP")
        self.actionOpenSSL = QtGui.QAction(MainWindow)
        self.actionOpenSSL.setCheckable(True)
        self.actionOpenSSL.setEnabled(False)
        self.actionOpenSSL.setObjectName("actionOpenSSL")
        self.actionDER = QtGui.QAction(MainWindow)
        self.actionDER.setCheckable(True)
        self.actionDER.setChecked(True)
        self.actionDER.setObjectName("actionDER")
        self.actionBase64 = QtGui.QAction(MainWindow)
        self.actionBase64.setCheckable(True)
        self.actionBase64.setObjectName("actionBase64")
        self.actionSignCheckOn = QtGui.QAction(MainWindow)
        self.actionSignCheckOn.setCheckable(True)
        self.actionSignCheckOn.setChecked(True)
        self.actionSignCheckOn.setObjectName("actionSignCheckOn")
        self.actionSignCheckOff = QtGui.QAction(MainWindow)
        self.actionSignCheckOff.setCheckable(True)
        self.actionSignCheckOff.setChecked(False)
        self.actionSignCheckOff.setObjectName("actionSignCheckOff")
        self.actionDettachedOn = QtGui.QAction(MainWindow)
        self.actionDettachedOn.setCheckable(True)
        self.actionDettachedOn.setObjectName("actionDettachedOn")
        self.actionDettachedOff = QtGui.QAction(MainWindow)
        self.actionDettachedOff.setCheckable(True)
        self.actionDettachedOff.setChecked(True)
        self.actionDettachedOff.setObjectName("actionDettachedOff")
        self.cryptoprovider.addAction(self.action_CSP)
        self.cryptoprovider.addAction(self.actionOpenSSL)
        self.encoding.addAction(self.actionDER)
        self.encoding.addAction(self.actionBase64)
        self.sign_check.addAction(self.actionSignCheckOn)
        self.sign_check.addAction(self.actionSignCheckOff)
        self.dettached.addAction(self.actionDettachedOn)
        self.dettached.addAction(self.actionDettachedOff)
        self.menu.addAction(self.cryptoprovider.menuAction())
        self.menu.addAction(self.encoding.menuAction())
        self.menu.addAction(self.sign_check.menuAction())
        self.menu.addAction(self.dettached.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "gost-crypto-gui", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSign.setStatusTip(QtGui.QApplication.translate("MainWindow", "Подписать указанный файл", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSign.setText(QtGui.QApplication.translate("MainWindow", "Подписать файл(ы)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVerify.setStatusTip(QtGui.QApplication.translate("MainWindow", "Проверить ЭЦП подписанного файла", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVerify.setText(QtGui.QApplication.translate("MainWindow", "Проверить подпись", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEncrypt.setStatusTip(QtGui.QApplication.translate("MainWindow", "Зашифровать указанный файл", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEncrypt.setText(QtGui.QApplication.translate("MainWindow", "Зашифровать файл(ы)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDecrypt.setStatusTip(QtGui.QApplication.translate("MainWindow", "Расшифровать файл", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDecrypt.setText(QtGui.QApplication.translate("MainWindow", "Расшифровать файл(ы)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Опции", None, QtGui.QApplication.UnicodeUTF8))
        self.cryptoprovider.setStatusTip(QtGui.QApplication.translate("MainWindow", "Выбрать используемый криптопровайдер", None, QtGui.QApplication.UnicodeUTF8))
        self.cryptoprovider.setTitle(QtGui.QApplication.translate("MainWindow", "Криптопровайдер", None, QtGui.QApplication.UnicodeUTF8))
        self.encoding.setTitle(QtGui.QApplication.translate("MainWindow", "Кодировка файлов", None, QtGui.QApplication.UnicodeUTF8))
        self.sign_check.setTitle(QtGui.QApplication.translate("MainWindow", "Авт. проверка подписи", None, QtGui.QApplication.UnicodeUTF8))
        self.dettached.setTitle(QtGui.QApplication.translate("MainWindow", "Отсоединенная подпись", None, QtGui.QApplication.UnicodeUTF8))
        self.action_CSP.setText(QtGui.QApplication.translate("MainWindow", "КриптоПро CSP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSSL.setText(QtGui.QApplication.translate("MainWindow", "OpenSSL", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDER.setText(QtGui.QApplication.translate("MainWindow", "DER", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBase64.setText(QtGui.QApplication.translate("MainWindow", "base64", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignCheckOn.setText(QtGui.QApplication.translate("MainWindow", "Включено", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignCheckOff.setText(QtGui.QApplication.translate("MainWindow", "Выключено", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDettachedOn.setText(QtGui.QApplication.translate("MainWindow", "Включено", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDettachedOff.setText(QtGui.QApplication.translate("MainWindow", "Выключено", None, QtGui.QApplication.UnicodeUTF8))

